# Generated by Django 5.1.4 on 2024-12-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_member_m_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_inform',
            fields=[
                ('f_no', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=10)),
                ('f_description', models.TextField()),
                ('f_location', models.CharField(max_length=30)),
                ('f_file', models.ImageField(null=True, upload_to='board')),
                ('f_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
    ]
