# Generated by Django 5.1.4 on 2024-12-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_inform',
            name='f_location',
        ),
    ]
