# Generated by Django 5.1.4 on 2024-12-12 08:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_food_inform_f_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('s_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('s_description', models.TextField(null=True)),
                ('s_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KR')),
                ('s_file', models.ImageField(null=True, upload_to='board/')),
                ('s_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food_inform')),
            ],
        ),
    ]
