# Generated by Django 5.1.4 on 2024-12-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='s_description',
        ),
    ]
