# Generated by Django 5.1.4 on 2024-12-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_store_s_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='s_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food_inform'),
        ),
        migrations.AlterField(
            model_name='store',
            name='s_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
