# Generated by Django 5.1.4 on 2024-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_store_s_member_alter_store_s_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('e_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
