# Generated by Django 5.1.4 on 2024-12-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_eat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='s_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.eat'),
        ),
    ]
