# Generated by Django 5.1.4 on 2024-12-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_store_s_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='s_member',
        ),
    ]
