# Generated by Django 5.1.4 on 2024-12-13 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_store_s_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='s_foodname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food_inform'),
        ),
    ]
