# Generated by Django 5.1.3 on 2024-12-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package_infrom',
            fields=[
                ('p_no', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.IntegerField()),
            ],
        ),
    ]
