# Generated by Django 5.1.3 on 2024-12-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_infrom',
            name='p_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
