# Generated by Django 5.1.4 on 2024-12-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0005_alter_location_inform_l_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_inform',
            name='l_description2',
            field=models.TextField(null=True),
        ),
    ]
