# Generated by Django 5.1.4 on 2024-12-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0006_alter_location_inform_l_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_inform',
            name='l_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location_inform',
            name='l_description2',
            field=models.CharField(max_length=1000),
        ),
    ]
