# Generated by Django 5.1.4 on 2024-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0014_remove_location_inform_l_attraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_inform',
            name='l_subtitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
