# Generated by Django 5.1.4 on 2024-12-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0016_location1'),
        ('member', '0002_alter_member_m_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_inform',
            name='l_like_members',
            field=models.ManyToManyField(default='', related_name='like_member', to='member.member'),
        ),
    ]
