# Generated by Django 5.1.4 on 2024-12-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0008_alter_location_inform_l_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_inform',
            name='l_description2',
            field=models.CharField(default='Default Description', max_length=255),
        ),
    ]
