# Generated by Django 5.1.4 on 2024-12-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0010_alter_location_inform_l_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lo_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='location_inform',
            name='l_description2',
            field=models.CharField(default='Default Description', max_length=3000),
        ),
    ]
