# Generated by Django 5.1.4 on 2024-12-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0011_location_alter_location_inform_l_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('a_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('a_description', models.TextField(null=True)),
                ('a_file', models.ImageField(null=True, upload_to='board/')),
            ],
        ),
        migrations.RemoveField(
            model_name='location_inform',
            name='l_description2',
        ),
        migrations.RemoveField(
            model_name='location_inform',
            name='l_name',
        ),
        migrations.AlterField(
            model_name='location_inform',
            name='l_file',
            field=models.ImageField(null=True, upload_to='board/'),
        ),
    ]
