# Generated by Django 5.1.4 on 2024-12-10 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0012_attraction_remove_location_inform_l_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_inform',
            name='l_attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inside.attraction'),
        ),
    ]
